version: "2"

services:
  app:
    container_name: "prelive"
    image: "paolocremonese/wf-9.0.2.final:scndtry"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=cremonese
      - DB_NAME=telecloud
      - DB_USER=adminAgPVh9q
      - DB_PASS=8fRB2AWC92Mi
      - DB_URI=db:3306
      - OPENSHIFT_REPO_DIR=/opt/jboss/wildfly/standalone/lib/ext/
      - OPENSHIFT_MYSQL_DATASOURCE=telecloudDatasource
      - MYSQL_TCP_ADDR=172.20.0.2
      - MYSQL_TCP_PORT=3306
    depends_on:
      - db
    volumes:
      - /home/paolo/WebApplications/TeleCLOUD/prelive/userconfig/:/opt/jboss/userconfig/       # persistent data storage for user.config
      - /home/paolo/WebApplications/TeleCLOUD/prelive/clouddata/:/opt/jboss/installer/         # persistent data storage for TeleCloud-OFFLINE
    ports:
      - "8080:8080" # application
      - "8443:8443" # application SSL HTTPS
      - "9990:9990" # admin console

  db:
    container_name: "db-prelive"
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE=telecloud
      - MYSQL_USER=adminAgPVh9q
      - MYSQL_PASSWORD=8fRB2AWC92Mi
      - MYSQL_ROOT_PASSWORD=root
    volumes:
#      - ./workdir/db/init/:/docker-entrypoint-initdb.d/ # init database
      - /home/paolo/WebApplications/TeleCLOUD/prelive/mysqldata/:/var/lib/mysql/              # data storage
    ports:
      - "3306:3306"
      
  backup:
    container_name: "pl-backup"
    image: databack/mysql-backup
    restart: always
    user: "0"
    volumes:
      - /home/paolo/WebApplications/TeleCLOUD/prelive/mysqlbkp/:/db/                          # database BACKUP
      - /home/paolo/WebApplications/TeleCLOUD/prelive/scripts.d/pre-backup/:/scripts.d/pre-backup/             # PREBACKUP script
      - /home/paolo/WebApplications/TeleCLOUD/prelive/scripts.d/post-backup/:/scripts.d/post-backup/           # POSTBACKUP script
    environment:
      - DB_DUMP_TARGET=" /db smb://193.100.100.204/Sharing/disk1/TeleCLOUD/prelive "  # ATTENZIONE, Ã¨ necessario uno spazio dopo il primo doppio apice e prima del d.a. finale !!!!!
      - SMB_USER=cremonese
      - SMB_PASS=Teledata011
      - DB_USER=adminAgPVh9q
      - DB_PASS=8fRB2AWC92Mi
      - DB_DUMP_BEGIN=0825                    # WARNING .. USE GMT TIME !!!
      - DB_SERVER=db
      - DB_DUMP_DEBUG=true
      - DB_DUMP_SAFECHARS=true
    depends_on:
      - db
      - app
         

#networks:
#    default:
#        driver: bridge
   
networks:
    default:
        driver: bridge
        ipam:
            config:
              - subnet: 172.20.0.0/24
                gateway: 172.20.0.1
        
